# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-20 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patchwork', '0020_tag_show_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=256)),
                ('ref_match', models.CharField(max_length=256)),
                ('ref_url_format', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patch',
            options={'base_manager_name': 'objects', 'verbose_name_plural': 'Patches'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('date',), 'verbose_name_plural': 'Series'},
        ),
    ]
